pipeline {
    stages {
        stage('dev') {
            echo "dev env"
        }
        stage('qa') {
            echo "qa env"
        }
        stage('prod') {
            echo "prod env"
        }
    }
}
